// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: probuf/oraclenodeservice.proto

package probuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// messages for initial connection
type AckClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack bool `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *AckClient) Reset() {
	*x = AckClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_probuf_oraclenodeservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckClient) ProtoMessage() {}

func (x *AckClient) ProtoReflect() protoreflect.Message {
	mi := &file_probuf_oraclenodeservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckClient.ProtoReflect.Descriptor instead.
func (*AckClient) Descriptor() ([]byte, []int) {
	return file_probuf_oraclenodeservice_proto_rawDescGZIP(), []int{0}
}

func (x *AckClient) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

// messages for initial connection
type AckServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack       bool   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	RequestId uint64 `protobuf:"varint,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
}

func (x *AckServer) Reset() {
	*x = AckServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_probuf_oraclenodeservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckServer) ProtoMessage() {}

func (x *AckServer) ProtoReflect() protoreflect.Message {
	mi := &file_probuf_oraclenodeservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckServer.ProtoReflect.Descriptor instead.
func (*AckServer) Descriptor() ([]byte, []int) {
	return file_probuf_oraclenodeservice_proto_rawDescGZIP(), []int{1}
}

func (x *AckServer) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *AckServer) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

// messages for request
type RequestFromClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId uint64 `protobuf:"varint,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
}

func (x *RequestFromClient) Reset() {
	*x = RequestFromClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_probuf_oraclenodeservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestFromClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFromClient) ProtoMessage() {}

func (x *RequestFromClient) ProtoReflect() protoreflect.Message {
	mi := &file_probuf_oraclenodeservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFromClient.ProtoReflect.Descriptor instead.
func (*RequestFromClient) Descriptor() ([]byte, []int) {
	return file_probuf_oraclenodeservice_proto_rawDescGZIP(), []int{2}
}

func (x *RequestFromClient) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type ResponseToClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IotId         string `protobuf:"bytes,1,opt,name=iotId,proto3" json:"iotId,omitempty"`
	RequestId     uint64 `protobuf:"varint,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequireResult bool   `protobuf:"varint,3,opt,name=requireResult,proto3" json:"requireResult,omitempty"`
}

func (x *ResponseToClient) Reset() {
	*x = ResponseToClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_probuf_oraclenodeservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseToClient) ProtoMessage() {}

func (x *ResponseToClient) ProtoReflect() protoreflect.Message {
	mi := &file_probuf_oraclenodeservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseToClient.ProtoReflect.Descriptor instead.
func (*ResponseToClient) Descriptor() ([]byte, []int) {
	return file_probuf_oraclenodeservice_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseToClient) GetIotId() string {
	if x != nil {
		return x.IotId
	}
	return ""
}

func (x *ResponseToClient) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ResponseToClient) GetRequireResult() bool {
	if x != nil {
		return x.RequireResult
	}
	return false
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IotId         string `protobuf:"bytes,1,opt,name=iotId,proto3" json:"iotId,omitempty"`
	RequestId     uint64 `protobuf:"varint,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequireResult bool   `protobuf:"varint,3,opt,name=requireResult,proto3" json:"requireResult,omitempty"`
	ActualResult  bool   `protobuf:"varint,4,opt,name=actualResult,proto3" json:"actualResult,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_probuf_oraclenodeservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_probuf_oraclenodeservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_probuf_oraclenodeservice_proto_rawDescGZIP(), []int{4}
}

func (x *Result) GetIotId() string {
	if x != nil {
		return x.IotId
	}
	return ""
}

func (x *Result) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Result) GetRequireResult() bool {
	if x != nil {
		return x.RequireResult
	}
	return false
}

func (x *Result) GetActualResult() bool {
	if x != nil {
		return x.ActualResult
	}
	return false
}

type Receipt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId   uint64 `protobuf:"varint,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	ReceiptHash uint64 `protobuf:"varint,2,opt,name=receiptHash,proto3" json:"receiptHash,omitempty"`
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_probuf_oraclenodeservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_probuf_oraclenodeservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_probuf_oraclenodeservice_proto_rawDescGZIP(), []int{5}
}

func (x *Receipt) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Receipt) GetReceiptHash() uint64 {
	if x != nil {
		return x.ReceiptHash
	}
	return 0
}

var File_probuf_oraclenodeservice_proto protoreflect.FileDescriptor

var file_probuf_oraclenodeservice_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x70, 0x72, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x1d, 0x0a, 0x09, 0x41, 0x63, 0x6b, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x22, 0x3b, 0x0a, 0x09, 0x41, 0x63, 0x6b, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46,
	0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x6c, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6f, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6f, 0x74, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x24, 0x0a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x86, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x69, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63,
	0x74, 0x75, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x49,
	0x0a, 0x07, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x70, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x70, 0x74, 0x48, 0x61, 0x73, 0x68, 0x32, 0xcb, 0x01, 0x0a, 0x11, 0x4f, 0x72,
	0x61, 0x63, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x39, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x63, 0x6b, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0b, 0x53, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x00,
	0x12, 0x35, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x70, 0x74, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x70, 0x72, 0x6f, 0x62,
	0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_probuf_oraclenodeservice_proto_rawDescOnce sync.Once
	file_probuf_oraclenodeservice_proto_rawDescData = file_probuf_oraclenodeservice_proto_rawDesc
)

func file_probuf_oraclenodeservice_proto_rawDescGZIP() []byte {
	file_probuf_oraclenodeservice_proto_rawDescOnce.Do(func() {
		file_probuf_oraclenodeservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_probuf_oraclenodeservice_proto_rawDescData)
	})
	return file_probuf_oraclenodeservice_proto_rawDescData
}

var file_probuf_oraclenodeservice_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_probuf_oraclenodeservice_proto_goTypes = []interface{}{
	(*AckClient)(nil),         // 0: probuf.AckClient
	(*AckServer)(nil),         // 1: probuf.AckServer
	(*RequestFromClient)(nil), // 2: probuf.RequestFromClient
	(*ResponseToClient)(nil),  // 3: probuf.ResponseToClient
	(*Result)(nil),            // 4: probuf.Result
	(*Receipt)(nil),           // 5: probuf.Receipt
}
var file_probuf_oraclenodeservice_proto_depIdxs = []int32{
	0, // 0: probuf.OracleNodeService.CheckForRequest:input_type -> probuf.AckClient
	2, // 1: probuf.OracleNodeService.SendRequest:input_type -> probuf.RequestFromClient
	4, // 2: probuf.OracleNodeService.ResponseDelivery:input_type -> probuf.Result
	1, // 3: probuf.OracleNodeService.CheckForRequest:output_type -> probuf.AckServer
	3, // 4: probuf.OracleNodeService.SendRequest:output_type -> probuf.ResponseToClient
	5, // 5: probuf.OracleNodeService.ResponseDelivery:output_type -> probuf.Receipt
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_probuf_oraclenodeservice_proto_init() }
func file_probuf_oraclenodeservice_proto_init() {
	if File_probuf_oraclenodeservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_probuf_oraclenodeservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_probuf_oraclenodeservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_probuf_oraclenodeservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestFromClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_probuf_oraclenodeservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseToClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_probuf_oraclenodeservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_probuf_oraclenodeservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Receipt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_probuf_oraclenodeservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_probuf_oraclenodeservice_proto_goTypes,
		DependencyIndexes: file_probuf_oraclenodeservice_proto_depIdxs,
		MessageInfos:      file_probuf_oraclenodeservice_proto_msgTypes,
	}.Build()
	File_probuf_oraclenodeservice_proto = out.File
	file_probuf_oraclenodeservice_proto_rawDesc = nil
	file_probuf_oraclenodeservice_proto_goTypes = nil
	file_probuf_oraclenodeservice_proto_depIdxs = nil
}
